### PR TITLE
encode non-printable body in hex

### PR DESCRIPTION
**Pull request by Kriechi**

### CODE REVIEW

**Comment by Lukasa** [comment]
This is an interesting idea, but I wonder if it wouldn't be more effective if you used the string `repr` instead: `body = repr(self.serialize_body())`. How do you feel about that?

**Comment by Kriechi** [comment]
Usually I'm not interessted in the body of a data frame (mostly plain text anyway), but in one of the other frame types (headers, error codes, etc).

I think this is not very readable or intuitive to understand:
```python
>>> repr(b"\x02\x10\x32\x41\x42\x43\x44")
"'\\x02\\x102ABCD'"
```

where as this is much better IMHO:
```python
>>> b"\x02\x10\x32\x41\x42\x43\x44".encode('hex')
'02103241424344'
```

**Comment by Lukasa** [comment]
@Kriechi That's fair. In that case, you'll need to fix the test breakage. =)

**Comment by Kriechi** [comment]
Done.

**Comment by Lukasa** [comment]
\o/

**Pull request merged**
